### ISSUE TITLE
How to get Surah type?

### ISSUE THREAD

**Issue by takasurazeem** [TazkiyaTech/quran-sdk#1]
How to know if it is either a Makki surah or Madni surah?

**Comment by adil-hussain-84** [comment]
Unfortunately this information is not exposed through the library's Android and iOS APIs nor is it in the SQlite database which the Android and iOS library's use under-the-hood.

You're best adding this information directly into your application projects. For some guidance as to which Surahs are Makki and which are Madani, refer to the `type` attributes in the `surahs.surah` elements in the [quran-metadata.xml](https://github.com/TazkiyaTech/quran-sdk/blob/master/extras/quran-metadata.xml) file.
